version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/server/lockpage-full-stack-starter
file_exists_behavior: OVERWRITE
hooks:
  # ApplicationStop:          # Gracefully stop or remove previous
  BeforeInstall:              # Before agent copies files
    - location: scripts/install_dependencies.sh
      timeout: 120
      # runas: ubuntu         # Changed codedeploy agent to run as ubuntu
  AfterInstall:               # Configure app, permissions
    - location: scripts/populate_secrets.sh
      timeout: 120
  ApplicationStart:           # Start app, restart stopped services
    - location: scripts/start_server.sh
      timeout: 300
      # runas: ubuntu         # Changed codedeploy agent to run as ubuntu
  # ValidateService:          # Verify deployment
  # BeforeBlockTraffic:       # Before deregistering from LB
  # AfterBlockraffic:         # After deregistering from LB
  # BeforeAllowTraffic:       # Before registering with LB
  # AfterAllowTraffic:        # After registering with LB
