#
# run-PR-tests.yml
#

name: Run tests on PR

on:
  pull_request:
    branches:
      - master
  
jobs:
  
  run-PR-tests:

    name: Run PR tests
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_PURPOSE: 'PR-test'
      GHA_REPO_NAME: 'lockpage-full-stack-starter-private'
      OVERRIDE_DB_PORT: '5432'
      OVERRIDE_PORT: '80'
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install yarn and pm2
      run: |
        npm install -g yarn
        yarn global add pm2
    
    - name: Unlock ports <1024 for node
      run: |
        sudo setcap cap_net_bind_service=+ep $(command -v node)

    - name: Install packages
      run: |
        yarn install --frozen-lockfile
        
    - name: Populate production secrets with test values
      run: |
        yarn script:secrets:test:gh
    
    - name: Setup dev database
      run: |
        yarn db:dev:setup
    
    - name: Build code
      run: |
        yarn build:all:dev
        
    - name: Start server (dev/PR)
      id: server
      run: |
        yarn start:PR
    
    - name: Run all jest tests
      run: |
        yarn jest:all:prod
